# Generated by Django 3.0.3 on 2020-03-03 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okboomerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OkBoomer',
            new_name='Boom',
        ),
    ]
