# Generated by Django 3.0.3 on 2020-03-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okboomerapp', '0002_auto_20200303_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='boom',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
